include:
 - net.yaml
 - storage.yaml

services:
  postfix:
    image: boky/postfix
    container_name: postfix
    restart: unless-stopped
    environment:
      - ALLOWED_SENDER_DOMAINS=smtp.local
      - ALLOW_EMPTY_SENDER_DOMAINS=true
      # - VIRTUAL_ALIAS_DOMAINS=smtp.local
      # - VIRTUAL_ALIAS_MAPS=@smtp.local:usuario@smtp.local
      # - VIRTUAL_ALIAS_MAPS=@smtp.local:usuario@smtp.local,zitadel@smtp.local:usuario@smtp.local
      - ENABLE_SASLAUTHD=yes
      - SASLAUTHD_MECHANISMS=plain,login
      - SMTPD_SASL_USERS=usuario@smtp.local:senha
      - SMTP_TLS_SECURITY_LEVEL=may
      - SMTPD_TLS_SECURITY_LEVEL=may
      - SMTPD_TLS_AUTH_ONLY=yes
      - SMTPD_SASL_AUTH_ENABLE=yes
      - SMTPD_SASL_SECURITY_OPTIONS=noanonymous
      # - SMTPD_RELAY_RESTRICTIONS=permit_mynetworks,permit_sasl_authenticated,reject_unauth_destination
      - RELAYHOST=smtp.local:1025
      # - POSTFIX_myhostname=smtp.local
      # - HOSTNAME=smtp.loca
      # - MYDESTINATION=localhost,smtp.local
      # - ALLOWED_SENDER_DOMAINS=postfix
      # - ALLOW_UNQUALIFIED_SENDERS=1
      # - VIRTUAL_ALIAS_DOMAINS=postfix
      # - VIRTUAL_ALIAS_MAPS=@postfix:usuario@postfix
      # - ENABLE_SASLAUTHD=yes
      # - SASLAUTHD_MECHANISMS=plain,login
      # - SMTPD_SASL_USERS=usuario@postfix:senha
      # - SMTP_TLS_SECURITY_LEVEL=may
      # - SMTPD_TLS_SECURITY_LEVEL=may
      # - SMTPD_TLS_AUTH_ONLY=yes
      # - SMTPD_SASL_AUTH_ENABLE=yes
      # - SMTPD_SASL_SECURITY_OPTIONS=noanonymous
      # - SMTPD_RELAY_RESTRICTIONS=permit_mynetworks,permit_sasl_authenticated,reject_unauth_destination
      # - SMTPD_RECIPIENT_RESTRICTIONS=reject_non_fqdn_recipient,reject_unknown_recipient_domain,permit_sasl_authenticated,reject_unauth_destination
    # ports:
    #   - "25:25"
    #   - 587:587
    # extra_hosts:
    #   - "smtp.local:127.0.0.1"
    networks:
      - smtpnet

  dashboard:
    image: axllent/mailpit:latest
    container_name: dashboard
    hostname: smtp.local
    restart: unless-stopped
    networks:
      - smtpnet
    # ports:
    #   - "1025:1025"  # SMTP
    #   - "8025:8025"  # Web UI
    volumes:
      - smtpdata:/data
    environment:
      MP_SMTP_AUTH_ALLOW_INSECURE: "true"
      # MP_SMTP_AUTH_USERNAME: "zitadel"
      # MP_SMTP_AUTH_PASSWORD: "test123"
      MP_DATA_FILE: /data/mailpit.db
      MP_UI_BIND_ADDR: "0.0.0.0:8025"
      MP_SMTP_BIND_ADDR: "0.0.0.0:1025"
