# DefaultInstance:
  # DomainPolicy:
  #   SMTPSenderAddressMatchesInstanceDomain: false
  # SMTPConfiguration:
  #   SMTP:
  #     Host: "postfix:587"
  #     User: "usuario@smtp.local"
  #     Password: "senha"

Database:
  cockroach:
    Host: roach-lb
    Port: 26257
    Database: zitadel
    MaxOpenConns: 20
    MaxConnLifetime: 30m
    MaxConnIdleTime: 30m
    Options: ""
    User:
      Username: zitadel
      Password: ""
      SSL:
        Mode: "verify-full"
        RootCert: "/run/secrets/ca.crt"
        Cert: "/run/secrets/client.zitadel.crt"
        Key: "/run/secrets/client.zitadel.key"
    Admin:
      Username: root
      Password: ""
      SSL:
        Mode: "verify-full"
        RootCert: "/run/secrets/ca.crt"
        Cert: "/run/secrets/client.root.crt"
        Key: "/run/secrets/client.root.key"
